//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetteAPIClientSDKUnitTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class StagingAssette : global::System.Configuration.ApplicationSettingsBase {
        
        private static StagingAssette defaultInstance = ((StagingAssette)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StagingAssette())));
        
        public static StagingAssette Default {
            get {
                return defaultInstance;
            }
        }
    }
}
